# src/OC/CoreBundle/Resources/config/routing.yml

oc_core_homepage:
    path: /
    defaults:
        _controller: OCCoreBundle:CoreBundle:index
    requirements:
        format: html|xml
        
oc_core_contact:
    path:     /contact
    defaults: { _controller: OCCoreBundle:CoreBundle:contact }
    requirements:
        format: html|xml
